docker: &docker
  docker:
    - image: circleci/node:8.9

macos: &macos
  macos:
    xcode: "9.1.0" # Node 8.9

root: &root
  working_directory: ~/repo

tagged: &tagged
  filters:
    tags:
      only: /^v.*/
    branches:
      ignore: /.*/

any: &any
  filters:
    tags:
      only: /.*/

version: 2
jobs:
  build_macos:
    <<: *macos
    <<: *root

    steps:
      - checkout
      - restore_cache:
          keys:
          - v2-dependencies-{{ checksum "package.json" }}
          # fallback to using the latest cache if no exact match is found
          - v2-dependencies-

      - run: yarn install --pure-lockfile
      - save_cache:
          paths:
            - node_modules
          key: v2-dependencies-{{ checksum "package.json" }}
      - run: yarn test

  build_linux:
    <<: *docker
    <<: *root

    steps:
      - checkout
      - run: yarn install --pure-lockfile
      - run: yarn test

  publish:
    <<: *docker
    <<: *root

    steps:
      - checkout
      - run: yarn install --pure-lockfile
      - run: npm publish --access public

workflows:
  version: 2
  build:
    jobs:
      - build_macos:
          <<: *any
      # Not build on linux rn, https://github.com/electron/spectron/issues/323
      # - build_linux:
      #     <<: *any
      - publish:
          <<: *tagged
          requires:
            - build_macos